#Tue Nov 26 11:54:47 EET 2024
junitVersion=5.11.3
keycloakVersion=26.3.3
org.gradle.configuration-cache=true
testContainersKeycloakVersion=3.6.0
testContainersVersion=1.20.4
awaitilityVersion=4.3.0
seleniumRemoteDriverVersion=4.26.0
seleniumVersion=4.26.0
version=0.9.10-SNAPSHOT
jacocoVersion=0.8.13
